version: "3.9"

services:

  mongo:
    image: mongo:6
    container_name: catalog-mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: catalogdb
    ports:
      - "27017:27017"

  backend:
    build: ./back-end
    container_name: catalog-backend
    restart: always
    env_file:
      - ./back-end/.env
    depends_on:
      - mongo
    command: >
      sh -c "
      npm install &&
      npm run seed &&
      npm run start:dev
      "
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/app
      - /app/node_modules

  frontend:
    build: ./front-end
    container_name: catalog-frontend
    restart: always
    env_file:
      - ./front-end/.env
    depends_on:
      - backend
    command: >
      sh -c "
      npm install &&
      npm run serve
      "
    ports:
      - "8080:8080"
    volumes:
      - ./front-end:/app
      - /app/node_modules

volumes:
  mongo-data:
